name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21 and Gradle
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Initialize Gradle project (if not present)
      run: gradle init --type java-library

    - name: Install Gradle
      run: |
        sudo apt-get install -y unzip
        export GRADLE_VERSION=8.5
        wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
        unzip -d /opt/gradle gradle-${GRADLE_VERSION}-bin.zip
        export PATH=$PATH:/opt/gradle/gradle-${GRADLE_VERSION}/bin
        
    - name: Find Java Files Compile Java code
      run: |
        gradle clean
        gradle findJavaFiles
        gradle build
